### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by CholoTook** [eriqande/snppit#4]
Hello, Is this project still maintained?

Many thanks,
Dan.

**Comment by eriqande** [comment]
Yes.  Still maintained.  Not many updates recently, but it is still used by several groups.

**Comment by CholoTook** [comment]
Thanks so much for the quick reply Eric!

I'm really sorry, I confused this project with this: https://thesnppit.net/!!

**Comment by eriqande** [comment]
No problem, thanks!
