### ISSUE TITLE
converting plink's bed files to snppit input?

### ISSUE THREAD

**Issue by ckastall** [eriqande/snppit#6]
Is there by any chance a script or tool available to quickly prepare snppit input file? For instance, when starting from a VCF file or plink's bed (+fam +bim) files?

Plink's bed file format: https://www.cog-genomics.org/plink/1.9/formats#bed

Thank you

**Comment by eriqande** [comment]
Hey ckastall, 

sorry I missed this until now.  

I don't have a script for that.  I would plink recode the bed file into a text based ped file and then use awk. 

If coming from a VCF file I would use bcftools query to extract everything into a decent text representation of the genotypes and then use awk or R to transpose, as needed.  

Cheers,

eric
